### ISSUE TITLE
Network redistributed mode

### ISSUE THREAD

**Issue by omarcostahamido** [iccmr-quantum/OSC-Qasm#29]
As discussed with @Itaborala today, one direction to explore now is to check how OSC-Qasm can play a role in networked scenarios where the flow of information between client requesting the job and the client receiving the results can traverse different computers in the (local or wide area) network, and different applications typologies other than Max.

The solution to this precise challenge in this issue might be less in a code change and more in a documentation change, as we instruct user on the steps required to remotely connect machines across the internet, for example.

(Tagging @scottoshiro2 since this might be of interest to him as well)

OCH

**TODO**

- [x] retrieve local IP. In fact, we should drop the 127.0.0.1 on [line 139](https://github.com/iccmr-quantum/OSC-Qasm/blob/6bcfe69022d1414ff8af8a7761c17ed301529e0b/osc_qasm.py#L139) and replace it permanently with the local IP.
  - [x] if the machine is not connected to a local network it ([socket](https://docs.python.org/3/library/socket.html)) will throw an error (following [this code](https://www.delftstack.com/howto/python/get-ip-address-python/)), and then later return `0.0.0.0` which can be swapped for `127.0.0.1`...
- [x] this is leading to version 1.3.0, need to change the version everywhere!
- [x] also update the readme and add a new section to explain what the user needs to do to work with this in a network scenario

**Comment by omarcostahamido** [comment]
@Itaborala I've been updating the first post with a TODO. please let me know if I am missing something we should also double check before the v1.3.0 release.

**Comment by Itaborala** [comment]
@omarcostahamido Does the third item really need fixing? 

The osc_qasm.py only listens to one IP address at once, so the --remote mode will make it listen to the router's local IP. The "First Machine" just needs to send their info through that IP and not localhost. 
It just occured to me that nothing is stopping us from running several instances of the python script - in other words, one for 127.0.0.1 and other for local_ip

Maybe I didn't undestand the problem?

**Comment by omarcostahamido** [comment]
> Does the third item really need fixing?

Nope. My bad, I started writing these as we were discussing how to solve the problem with `--offline`.

**Comment by Itaborala** [comment]
Ok! I've updated the documentation. Please let me know your thoughts about the README.md
(also secretly made a few changes in some --help entries)

> haha. tru dat! I can't help but to think that it does make working with this a little bit cumbersome. And indeed our workaround today to fix a single ip address to listen to as well. In nodejs I can startup a server and it listens on the specified port in any of the ip addresses for all the network adapters with no problem. I'm baffled at how complicated python makes this process...

Well, the python-osc implementation might not have gone that far...Or there's some solution we missed.

**Comment by omarcostahamido** [comment]
Go ahead and create a draft PR and assign me as reviewer please.
